import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Menu from '@/components/panel/Menu'



export default function Home() {
  return (
    <>
      <Head>
        <title>MARKETPLACE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>SOMOS UN MARKET NO VENDEMOS DROGAS</p>
          <Menu/>
        </div>
      </main>
    </>
  )
}
